"""initial_schema_all_tables

Revision ID: 0846970e5b1f
Revises: 
Create Date: 2026-01-16 07:49:43.519377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0846970e5b1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name_tw', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('dept', sa.String(length=100), nullable=True),
    sa.Column('department_code', sa.String(length=8), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('address1', sa.String(length=200), nullable=True),
    sa.Column('address2', sa.String(length=200), nullable=True),
    sa.Column('phone1', sa.String(length=20), nullable=True),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('spouse_name', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=20), nullable=True),
    sa.Column('identity_number', sa.String(length=32), nullable=True),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.Column('dorm_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department_code'), 'employees', ['department_code'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_identity_number'), 'employees', ['identity_number'], unique=True)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_code', sa.String(length=10), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('employee_name', sa.String(length=100), nullable=True),
    sa.Column('job_level', sa.String(length=50), nullable=True),
    sa.Column('nation', sa.String(length=10), nullable=True),
    sa.Column('dept_code', sa.String(length=20), nullable=True),
    sa.Column('dept_name', sa.String(length=200), nullable=True),
    sa.Column('grade_code', sa.String(length=20), nullable=True),
    sa.Column('grade_name', sa.String(length=100), nullable=True),
    sa.Column('init_score', sa.String(length=20), nullable=True),
    sa.Column('init_comment', sa.Text(), nullable=True),
    sa.Column('init_reviewer', sa.String(length=20), nullable=True),
    sa.Column('review_score', sa.String(length=20), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('review_reviewer', sa.String(length=20), nullable=True),
    sa.Column('final_score', sa.String(length=20), nullable=True),
    sa.Column('final_comment', sa.Text(), nullable=True),
    sa.Column('final_reviewer', sa.String(length=20), nullable=True),
    sa.Column('mgr_init_score', sa.String(length=20), nullable=True),
    sa.Column('mgr_init_comment', sa.Text(), nullable=True),
    sa.Column('mgr_init_reviewer', sa.String(length=20), nullable=True),
    sa.Column('mgr_review_score', sa.String(length=20), nullable=True),
    sa.Column('mgr_review_comment', sa.Text(), nullable=True),
    sa.Column('mgr_review_reviewer', sa.String(length=20), nullable=True),
    sa.Column('mgr_final_score', sa.String(length=20), nullable=True),
    sa.Column('mgr_final_comment', sa.Text(), nullable=True),
    sa.Column('mgr_final_reviewer', sa.String(length=20), nullable=True),
    sa.Column('leave_days', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_code', 'employee_id', name='uq_evaluations_term_employee')
    )
    op.create_index(op.f('ix_evaluations_dept_code'), 'evaluations', ['dept_code'], unique=False)
    op.create_index('ix_evaluations_employee_id', 'evaluations', ['employee_id'], unique=False)
    op.create_index('ix_evaluations_term_code', 'evaluations', ['term_code'], unique=False)
    op.create_table('pidms_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyname', sa.String(length=255), nullable=False),
    sa.Column('keyname_with_dash', sa.String(length=255), nullable=False),
    sa.Column('prd', sa.String(length=255), nullable=False),
    sa.Column('eid', sa.String(length=255), nullable=True),
    sa.Column('is_key_type', sa.String(length=50), nullable=True),
    sa.Column('is_retail', sa.Integer(), nullable=True),
    sa.Column('sub', sa.String(length=255), nullable=True),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Integer(), nullable=False),
    sa.Column('errorcode', sa.String(length=255), nullable=True),
    sa.Column('had_occurred', sa.Integer(), nullable=True),
    sa.Column('invalid', sa.Integer(), nullable=True),
    sa.Column('datetime_checked_done', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pidms_keys_blocked', 'pidms_keys', ['blocked'], unique=False)
    op.create_index('idx_pidms_keys_prd', 'pidms_keys', ['prd'], unique=False)
    op.create_index('idx_pidms_keys_remaining', 'pidms_keys', ['remaining'], unique=False)
    op.create_index(op.f('ix_pidms_keys_blocked'), 'pidms_keys', ['blocked'], unique=False)
    op.create_index(op.f('ix_pidms_keys_keyname'), 'pidms_keys', ['keyname'], unique=True)
    op.create_index(op.f('ix_pidms_keys_prd'), 'pidms_keys', ['prd'], unique=False)
    op.create_index(op.f('ix_pidms_keys_remaining'), 'pidms_keys', ['remaining'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('localId', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_localId'), 'users', ['localId'], unique=False)
    op.create_index(op.f('ix_users_social_id'), 'users', ['social_id'], unique=True)
    op.create_table('dormitory_bills',
    sa.Column('bill_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('term_code', sa.String(length=10), nullable=False),
    sa.Column('dorm_code', sa.String(length=20), nullable=False),
    sa.Column('factory_location', sa.String(length=100), nullable=True),
    sa.Column('elec_last_index', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('elec_curr_index', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('elec_usage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('elec_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('water_last_index', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_curr_index', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_usage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shared_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('management_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('elec_curr_index >= elec_last_index', name='chk_elec_index'),
    sa.CheckConstraint('total_amount >= 0 AND elec_amount >= 0 AND water_amount >= 0 AND shared_fee >= 0 AND management_fee >= 0', name='chk_amounts'),
    sa.CheckConstraint('water_curr_index >= water_last_index', name='chk_water_index'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('bill_id'),
    sa.UniqueConstraint('employee_id', 'term_code', 'dorm_code', name='uq_bill_entry')
    )
    op.create_index('idx_dormitory_bills_sort', 'dormitory_bills', ['term_code', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'term_code': 'DESC', 'created_at': 'DESC'})
    op.create_index(op.f('ix_dormitory_bills_dorm_code'), 'dormitory_bills', ['dorm_code'], unique=False)
    op.create_index(op.f('ix_dormitory_bills_employee_id'), 'dormitory_bills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_dormitory_bills_term_code'), 'dormitory_bills', ['term_code'], unique=False)
    op.create_index(op.f('ix_dormitory_bills_total_amount'), 'dormitory_bills', ['total_amount'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dormitory_bills_total_amount'), table_name='dormitory_bills')
    op.drop_index(op.f('ix_dormitory_bills_term_code'), table_name='dormitory_bills')
    op.drop_index(op.f('ix_dormitory_bills_employee_id'), table_name='dormitory_bills')
    op.drop_index(op.f('ix_dormitory_bills_dorm_code'), table_name='dormitory_bills')
    op.drop_index('idx_dormitory_bills_sort', table_name='dormitory_bills', postgresql_using='btree', postgresql_ops={'term_code': 'DESC', 'created_at': 'DESC'})
    op.drop_table('dormitory_bills')
    op.drop_index(op.f('ix_users_social_id'), table_name='users')
    op.drop_index(op.f('ix_users_localId'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pidms_keys_remaining'), table_name='pidms_keys')
    op.drop_index(op.f('ix_pidms_keys_prd'), table_name='pidms_keys')
    op.drop_index(op.f('ix_pidms_keys_keyname'), table_name='pidms_keys')
    op.drop_index(op.f('ix_pidms_keys_blocked'), table_name='pidms_keys')
    op.drop_index('idx_pidms_keys_remaining', table_name='pidms_keys')
    op.drop_index('idx_pidms_keys_prd', table_name='pidms_keys')
    op.drop_index('idx_pidms_keys_blocked', table_name='pidms_keys')
    op.drop_table('pidms_keys')
    op.drop_index('ix_evaluations_term_code', table_name='evaluations')
    op.drop_index('ix_evaluations_employee_id', table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_dept_code'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_employees_identity_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_code'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
