"""Create pidms_keys table

Revision ID: 341081d9ee36
Revises: d00945f93f23
Create Date: 2026-01-12 14:30:58.013777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341081d9ee36'
down_revision: Union[str, None] = 'd00945f93f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dormitory_bills_sort', table_name='dormitory_bills')
    op.create_index('idx_dormitory_bills_sort', 'dormitory_bills', ['term_code', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'term_code': 'DESC', 'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dormitory_bills_sort', table_name='dormitory_bills', postgresql_using='btree', postgresql_ops={'term_code': 'DESC', 'created_at': 'DESC'})
    op.create_index('idx_dormitory_bills_sort', 'dormitory_bills', [sa.text('term_code DESC'), sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
