"""Add pidms_keys table

Revision ID: 43e6802dc765
Revises: 341081d9ee36
Create Date: 2026-01-12 15:47:40.188978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e6802dc765'
down_revision: Union[str, None] = '341081d9ee36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pidms_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyname', sa.String(length=255), nullable=False),
    sa.Column('keyname_with_dash', sa.String(length=255), nullable=False),
    sa.Column('prd', sa.String(length=255), nullable=False),
    sa.Column('eid', sa.String(length=255), nullable=True),
    sa.Column('is_key_type', sa.String(length=50), nullable=True),
    sa.Column('is_retail', sa.Integer(), nullable=True),
    sa.Column('sub', sa.String(length=255), nullable=True),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Integer(), nullable=False),
    sa.Column('errorcode', sa.String(length=255), nullable=True),
    sa.Column('had_occurred', sa.Integer(), nullable=True),
    sa.Column('invalid', sa.Integer(), nullable=True),
    sa.Column('datetime_checked_done', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pidms_keys_blocked', 'pidms_keys', ['blocked'], unique=False)
    op.create_index('idx_pidms_keys_prd', 'pidms_keys', ['prd'], unique=False)
    op.create_index('idx_pidms_keys_remaining', 'pidms_keys', ['remaining'], unique=False)
    op.create_index(op.f('ix_pidms_keys_blocked'), 'pidms_keys', ['blocked'], unique=False)
    op.create_index(op.f('ix_pidms_keys_keyname'), 'pidms_keys', ['keyname'], unique=True)
    op.create_index(op.f('ix_pidms_keys_prd'), 'pidms_keys', ['prd'], unique=False)
    op.create_index(op.f('ix_pidms_keys_remaining'), 'pidms_keys', ['remaining'], unique=False)
    op.drop_index('idx_dormitory_bills_sort', table_name='dormitory_bills')
    op.create_index('idx_dormitory_bills_sort', 'dormitory_bills', ['term_code', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'term_code': 'DESC', 'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dormitory_bills_sort', table_name='dormitory_bills', postgresql_using='btree', postgresql_ops={'term_code': 'DESC', 'created_at': 'DESC'})
    op.create_index('idx_dormitory_bills_sort', 'dormitory_bills', [sa.text('term_code DESC'), sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_pidms_keys_remaining'), table_name='pidms_keys')
    op.drop_index(op.f('ix_pidms_keys_prd'), table_name='pidms_keys')
    op.drop_index(op.f('ix_pidms_keys_keyname'), table_name='pidms_keys')
    op.drop_index(op.f('ix_pidms_keys_blocked'), table_name='pidms_keys')
    op.drop_index('idx_pidms_keys_remaining', table_name='pidms_keys')
    op.drop_index('idx_pidms_keys_prd', table_name='pidms_keys')
    op.drop_index('idx_pidms_keys_blocked', table_name='pidms_keys')
    op.drop_table('pidms_keys')
    # ### end Alembic commands ###
