"""Add dormitory_bills table

Revision ID: d00945f93f23
Revises: 12f90a9790c8
Create Date: 2026-01-12 10:39:51.954658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd00945f93f23'
down_revision: Union[str, None] = '12f90a9790c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dormitory_bills',
    sa.Column('bill_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('term_code', sa.String(length=10), nullable=False),
    sa.Column('dorm_code', sa.String(length=20), nullable=False),
    sa.Column('factory_location', sa.String(length=100), nullable=True),
    sa.Column('elec_last_index', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('elec_curr_index', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('elec_usage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('elec_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('water_last_index', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_curr_index', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_usage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shared_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('management_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('elec_curr_index >= elec_last_index', name='chk_elec_index'),
    sa.CheckConstraint('total_amount >= 0 AND elec_amount >= 0 AND water_amount >= 0 AND shared_fee >= 0 AND management_fee >= 0', name='chk_amounts'),
    sa.CheckConstraint('water_curr_index >= water_last_index', name='chk_water_index'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('bill_id'),
    sa.UniqueConstraint('employee_id', 'term_code', 'dorm_code', name='uq_bill_entry')
    )
    op.create_index('idx_dormitory_bills_sort', 'dormitory_bills', ['term_code', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'term_code': 'DESC', 'created_at': 'DESC'})
    op.create_index(op.f('ix_dormitory_bills_dorm_code'), 'dormitory_bills', ['dorm_code'], unique=False)
    op.create_index(op.f('ix_dormitory_bills_employee_id'), 'dormitory_bills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_dormitory_bills_term_code'), 'dormitory_bills', ['term_code'], unique=False)
    op.create_index(op.f('ix_dormitory_bills_total_amount'), 'dormitory_bills', ['total_amount'], unique=False)
    op.drop_index('idx_metrics_db_name', table_name='metrics_history')
    op.drop_index('idx_metrics_db_type', table_name='metrics_history')
    op.drop_index('idx_metrics_timestamp', table_name='metrics_history')
    op.drop_table('metrics_history')
    op.drop_index('idx_employees_department_code', table_name='employees')
    op.drop_index('idx_employees_id', table_name='employees')
    op.drop_index('idx_employees_identity_number', table_name='employees')
    op.drop_constraint('uq_employees_identity_number', 'employees', type_='unique')
    op.create_index(op.f('ix_employees_department_code'), 'employees', ['department_code'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_identity_number'), 'employees', ['identity_number'], unique=True)
    op.drop_index('idx_users_localid', table_name='users')
    op.drop_constraint('uq_provider_social_id', 'users', type_='unique')
    op.create_index(op.f('ix_users_localId'), 'users', ['localId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_localId'), table_name='users')
    op.create_unique_constraint('uq_provider_social_id', 'users', ['provider', 'social_id'])
    op.create_index('idx_users_localid', 'users', ['localId'], unique=False)
    op.drop_index(op.f('ix_employees_identity_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_code'), table_name='employees')
    op.create_unique_constraint('uq_employees_identity_number', 'employees', ['identity_number'])
    op.create_index('idx_employees_identity_number', 'employees', ['identity_number'], unique=False)
    op.create_index('idx_employees_id', 'employees', ['id'], unique=False)
    op.create_index('idx_employees_department_code', 'employees', ['department_code'], unique=False)
    op.create_table('metrics_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('db_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type of metric: size, table_count, connections, etc.'),
    sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional metadata in JSON format'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='metrics_history_pkey'),
    comment='Stores historical metrics for database monitoring and trend analysis'
    )
    op.create_index('idx_metrics_timestamp', 'metrics_history', ['timestamp'], unique=False)
    op.create_index('idx_metrics_db_type', 'metrics_history', ['db_name', 'metric_type'], unique=False)
    op.create_index('idx_metrics_db_name', 'metrics_history', ['db_name'], unique=False)
    op.drop_index(op.f('ix_dormitory_bills_total_amount'), table_name='dormitory_bills')
    op.drop_index(op.f('ix_dormitory_bills_term_code'), table_name='dormitory_bills')
    op.drop_index(op.f('ix_dormitory_bills_employee_id'), table_name='dormitory_bills')
    op.drop_index(op.f('ix_dormitory_bills_dorm_code'), table_name='dormitory_bills')
    op.drop_index('idx_dormitory_bills_sort', table_name='dormitory_bills', postgresql_using='btree', postgresql_ops={'term_code': 'DESC', 'created_at': 'DESC'})
    op.drop_table('dormitory_bills')
    # ### end Alembic commands ###
